In [11]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

arr=np.array((1,2,3,4))
print(arr)
print(type(arr))


arr = np.array([[1,2,3,4,5],[5,4,3,2,1]])
print(arr)
print(type(arr))

arr=np.array(((1,2,3,4), (4,3,2,1)))
print(arr)
print(type(arr))
print(arr.ndim)

print(arr[1,1]+arr[1,2])



[1 2 3 4 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2 3 4 5]
 [5 4 3 2 1]]
<class 'numpy.ndarray'>
[[1 2 3 4]
 [4 3 2 1]]
<class 'numpy.ndarray'>
2
5
