In [1]:
x = range(3, 6)
for n in x:
  print(n)
  
import numpy as np
def square(x):
    return x * x
# note that &#37; is a percentage sign, and it needs to be replaced with actual percent symbol.`
x = np.random.randint(1, 10)
y = square(x)
print('squared is', (x, y))
y=np.random.randint(2,5)

3
4
5
squared is (2, 4)


In [23]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

arr=np.array((1,2,3,4))
print(arr)
print(type(arr))


arr = np.array([[1,2,3,4,5],[5,4,3,2,1]])
print(arr)
print(type(arr))

arr=np.array(((1,2,3,4), (4,3,2,1)))
print(arr)
print(type(arr))
print(arr.ndim)

print(arr[1,1]+arr[1,2])

import numpy
arr1 = numpy.array([[1,2,3],[4,5,6]])
arr2 = numpy.array([[1,2,3],[4,5,6]])
arr=numpy.concatenate((arr1, arr2), axis=0)
print(arr)

from numpy import random
y=random.rand(10)
x=random.randint(100)
z=random.randn(23)
print(x)
print(y)
print(z)

[1 2 3 4 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2 3 4 5]
 [5 4 3 2 1]]
<class 'numpy.ndarray'>
[[1 2 3 4]
 [4 3 2 1]]
<class 'numpy.ndarray'>
2
5
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
4
[0.01006148 0.10021944 0.83305735 0.40774549 0.97702053 0.9364936
 0.26051002 0.79133232 0.60015398 0.51352299]
[-0.95536907  0.09627115  2.59393019 -1.25189629 -0.90341403 -1.29101773
 -0.58790576  0.65577478  0.66587746  0.36857785  0.79765829  1.40011358
  0.02867106 -1.63128697 -1.27231847  1.5103443  -0.62088367  1.69201265
 -1.32203191 -1.71380447 -0.18459149 -0.65772788 -1.12183499]
