In [4]:
# Pandas is used for Data Structure, Data Analysis, Dataframe, DataSeries, DataSet

# Data Frame : DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.
# inbuild function DataFrame
import pandas as pd
import numpy as np


df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=["R1", "R2", "R3", "R4", "R5"],columns=["C1", "C2", "C3", "C4"])

print(df)

    C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19


In [5]:
print(df.head())

    C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19


In [8]:
df.head(3)
df.tail(2)

C1  C2  C3  C4
R4  12  13  14  15
R5  16  17  18  19

In [9]:
print(df.to_csv("1.csv"))
print(df.to_json("1.json"))
print(df.to_xml("1.xml"))
print(df.to_excel("1.xlsx"))
print(df.to_html("1.html"))

None
None
None
None
None


In [16]:
# Accessing the elements
# .loc : location; .iloc : index location

print(df.loc["R1"])

C1    0
C2    1
C3    2
C4    3
Name: R1, dtype: int32


In [21]:
print(df.iloc[:,:])
print()
print(df.iloc[1:2,2:3])

    C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15
R5  16  17  18  19

    C3
R2   6


In [25]:
# convert Dataframe into array

print(df.iloc[:,:].values)

print()
print(df.iloc[:,:].values.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

(5, 4)


In [26]:
# verify null value in dataframe

df.isnull().sum()

C1    0
C2    0
C3    0
C4    0
dtype: int64

In [27]:
print(df["C1"].value_counts(sort=True))

C1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [28]:
print(df["C1"].unique())

[ 0  4  8 12 16]


In [29]:
df["C3"]

R1     2
R2     6
R3    10
R4    14
R5    18
Name: C3, dtype: int32

In [32]:
df[["C3", "C2"]]

C3  C2
R1   2   1
R2   6   5
R3  10   9
R4  14  13
R5  18  17

In [35]:
# Reading CSV files
df=pd.read_csv("mercedesbenz.csv")
print(df)
df.head(5)

#info : how many object type, columns etc
#describe : mean, count



        ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0    

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [36]:
print(df.describe())

                ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     

In [37]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB
None


In [52]:
df1=pd.read_csv("data1.csv")
print(df1.head())
print()
df=pd.read_csv("data1.csv", sep="*")
print(df1.head())

          *C1  *C2*C3*C4
0  R1*1*2*3*4        NaN
1  R2*1*2*3*4        NaN
2  R3*1*2*3*4        NaN
3  R4*1*2*3*4        NaN
4  R5*1*2*3*4        NaN

          *C1  *C2*C3*C4
0  R1*1*2*3*4        NaN
1  R2*1*2*3*4        NaN
2  R3*1*2*3*4        NaN
3  R4*1*2*3*4        NaN
4  R5*1*2*3*4        NaN


In [60]:
df=pd.read_csv("mercedesbenz.csv")

print(df['X0'].value_counts(ascending=True))


X0
ab      1
ac      1
g       1
aa      2
q       2
c       3
ao      4
bc      6
r      10
as     10
au     11
b      11
k      11
ad     14
aw     16
l      16
u      17
i      18
am     18
aq     18
ax     19
a      21
at     25
ba     27
e      32
ai     34
m      34
af     35
v      36
al     67
d      73
h      75
ap    103
s     106
aj    151
az    175
j     181
w     182
n     195
f     227
o     269
x     300
t     306
ay    313
y     324
ak    349
z     360
Name: count, dtype: int64


In [65]:
print(df[df['ID']>100])

        ID       y  X0  X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
41     102   91.98   o   h  ae  f  d   j  j  b  ...     0     0     0     0   
42     106   98.08   z  aa  ai  c  d   j  g  j  ...     1     0     0     0   
43     107  139.20   w   s  as  c  d   j  i  q  ...     1     0     0     0   
44     108   85.44   s   z  ai  c  d   j  j  b  ...     1     0     0     0   
45     109  110.52   x   b   m  c  d   j  j  n  ...     0     0     1     0   
...    ...     ...  ..  ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak   s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j   o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak   v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al   r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z   r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
41      

In [76]:
#CSV

from io import StringIO, BytesIO

data=('col1,col2,col3,col4,col5\n'
      'x,y,z,a,10\n'
      'a,b,c,x,20\n'
      'm,n,o,,30')

In [67]:
type(data)

str

In [77]:
print(pd.read_csv(StringIO(data)))

  col1 col2 col3 col4  col5
0    x    y    z    a    10
1    a    b    c    x    20
2    m    n    o  NaN    30


In [85]:
df=pd.read_csv(StringIO(data))
print(df)
print()
df=pd.read_csv(StringIO(data),usecols=["col1","col3"])
print(df)
print()
df=pd.read_csv(StringIO(data),usecols=["col1","col3"],dtype=object)
print(df)
df=pd.read_csv(StringIO(data),usecols=["col1","col3"],dtype={"col1":str, "col3":str})
print(df)
df=pd.read_csv(StringIO(data),usecols=["col1","col3"], index_col=0)
print(df)


  col1 col2 col3 col4  col5
0    x    y    z    a    10
1    a    b    c    x    20
2    m    n    o  NaN    30

  col1 col3
0    x    z
1    a    c
2    m    o

  col1 col3
0    x    z
1    a    c
2    m    o
  col1 col3
0    x    z
1    a    c
2    m    o
     col3
col1     
x       z
a       c
m       o


In [82]:
df.dtypes

col1    object
col3    object
dtype: object